import type { Metadata } from "next";
import localFont from "next/font/local";
import "@repo/ui/globals.css";
import { MainLayout } from "@repo/ui/components/layout/main-layout";
import { VercelToolbar } from "@vercel/toolbar/next";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const shouldInjectToolbar = process.env.NODE_ENV === "development";
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <MainLayout className="w-full">{children}</MainLayout>
        {shouldInjectToolbar && <VercelToolbar />}
      </body>
    </html>
  );
}
